[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info
user=root

[program:funding-ingestion-live-worker]
command=/app/.venv/bin/funding-ingestion-live-worker --worker-id=live-worker-%(process_num)02d
numprocs=%(ENV_LIVE_INGESTION_WORKER_COUNT)s
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=10
