/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v0/funding-data/diff/historical_cumulative_differences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cumulative funding differences over a time period */
        get: operations["historical_cumulative_differences_api_v0_funding_data_diff_historical_cumulative_differences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/funding-data/diff/historical_differences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get historical funding differences over a time period with optional normalization */
        get: operations["historical_funding_differences_api_v0_funding_data_diff_historical_differences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/funding-data/diff/live_differences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get latest funding rate differences between contracts for the same asset */
        get: operations["funding_rate_differences_api_v0_funding_data_diff_live_differences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/funding-data/funding-wall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get funding wall matrix data */
        get: operations["funding_wall_api_v0_funding_data_funding_wall_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/funding-data/historical_avg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Average historical funding per contract over one or more day windows */
        get: operations["historical_avg_api_v0_funding_data_historical_avg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/funding-data/historical_latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest settled historical funding rate per contract for a filter slice */
        get: operations["historical_latest_api_v0_funding_data_historical_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/funding-data/historical_points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get historical funding points for a contract */
        get: operations["historical_points_api_v0_funding_data_historical_points_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/funding-data/live_latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest live funding rate per contract for a filter slice */
        get: operations["live_latest_api_v0_funding_data_live_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/funding-data/live_points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get aggregated live funding points for a contract */
        get: operations["live_points_api_v0_funding_data_live_points_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/funding-data/period_sums/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get funding sums for different time periods for a specific contract */
        get: operations["period_sums_api_v0_funding_data_period_sums__contract_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/meta/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Assets
         * @description Get all asset names that exist in contracts.
         *
         *     Returns assets sorted by market_cap_rank (ascending), then alphabetically
         *     for assets without market_cap_rank.
         */
        get: operations["get_assets_api_v0_meta_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/meta/contracts/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Contracts
         * @description Search contracts with prefix-aware scoring and fuzzy fallback.
         */
        get: operations["search_contracts_api_v0_meta_contracts_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/meta/contracts/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Contract Meta
         * @description Get single contract metadata by contract id.
         */
        get: operations["get_contract_meta_api_v0_meta_contracts__contract_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/meta/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quotes
         * @description Get all quote names ordered alphabetically.
         */
        get: operations["get_quotes_api_v0_meta_quotes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/meta/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sections
         * @description Get all section names ordered alphabetically.
         */
        get: operations["get_sections_api_v0_meta_sections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetNames */
        AssetNames: {
            /** Names */
            names: string[];
        };
        /** BaseResponse[AssetNames] */
        BaseResponse_AssetNames_: {
            data: components["schemas"]["AssetNames"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** BaseResponse[ContractMeta] */
        BaseResponse_ContractMeta_: {
            data: components["schemas"]["ContractMeta"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** BaseResponse[ContractSearchResults] */
        BaseResponse_ContractSearchResults_: {
            data: components["schemas"]["ContractSearchResults"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** BaseResponse[QuoteNames] */
        BaseResponse_QuoteNames_: {
            data: components["schemas"]["QuoteNames"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** BaseResponse[SectionNames] */
        BaseResponse_SectionNames_: {
            data: components["schemas"]["SectionNames"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** ContractMeta */
        ContractMeta: {
            /** Asset Name */
            asset_name: string;
            /** Deprecated */
            deprecated: boolean;
            /** Funding Interval */
            funding_interval: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Quote Name */
            quote_name: string;
            /** Section Name */
            section_name: string;
            /** Special Fields */
            special_fields: {
                [key: string]: unknown;
            };
            /** Synced */
            synced: boolean;
        };
        /** ContractSearchResult */
        ContractSearchResult: {
            /** Asset Name */
            asset_name: string;
            /** Asset Score */
            asset_score?: number | null;
            /** Funding Interval */
            funding_interval: number;
            /** Fuzzy Score */
            fuzzy_score?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Quote Name */
            quote_name: string;
            /** Quote Score */
            quote_score?: number | null;
            /** Relevance Score */
            relevance_score: number;
            /** Section Name */
            section_name: string;
            /** Section Score */
            section_score?: number | null;
        };
        /** ContractSearchResults */
        ContractSearchResults: {
            /** Contracts */
            contracts: components["schemas"]["ContractSearchResult"][];
        };
        /** CumulativeFundingDifference */
        CumulativeFundingDifference: {
            /** Abs Difference */
            abs_difference: number;
            /** Aligned From */
            aligned_from: number;
            /** Aligned To */
            aligned_to: number;
            /** Asset Name */
            asset_name: string;
            /**
             * Contract 1 Id
             * Format: uuid
             */
            contract_1_id: string;
            /** Contract 1 Quote */
            contract_1_quote: string;
            /** Contract 1 Section */
            contract_1_section: string;
            /** Contract 1 Total Funding */
            contract_1_total_funding: number;
            /**
             * Contract 2 Id
             * Format: uuid
             */
            contract_2_id: string;
            /** Contract 2 Quote */
            contract_2_quote: string;
            /** Contract 2 Section */
            contract_2_section: string;
            /** Contract 2 Total Funding */
            contract_2_total_funding: number;
            /** Difference */
            difference: number;
        };
        /** FundingPeriodSums */
        FundingPeriodSums: {
            /** Asset Name */
            asset_name: string;
            /**
             * Contract Id
             * Format: uuid
             */
            contract_id: string;
            /** Quote Name */
            quote_name: string;
            /** Section Name */
            section_name: string;
            /** Sum 14D */
            sum_14d: number | null;
            /** Sum 180D */
            sum_180d: number | null;
            /** Sum 30D */
            sum_30d: number | null;
            /** Sum 365D */
            sum_365d: number | null;
            /** Sum 7D */
            sum_7d: number | null;
            /** Sum 90D */
            sum_90d: number | null;
        };
        /**
         * FundingPoint
         * @description A single funding rate point.
         */
        FundingPoint: {
            /**
             * Contract Id
             * Format: uuid
             */
            contract_id: string;
            /** Funding Rate */
            funding_rate: number;
            /** Timestamp */
            timestamp: number;
        };
        /** FundingRateDifference */
        FundingRateDifference: {
            /** Abs Difference */
            abs_difference: number;
            /** Asset Name */
            asset_name: string;
            /** Contract 1 Funding Rate */
            contract_1_funding_rate: number;
            /**
             * Contract 1 Id
             * Format: uuid
             */
            contract_1_id: string;
            /** Contract 1 Quote */
            contract_1_quote: string;
            /** Contract 1 Section */
            contract_1_section: string;
            /** Contract 2 Funding Rate */
            contract_2_funding_rate: number;
            /**
             * Contract 2 Id
             * Format: uuid
             */
            contract_2_id: string;
            /** Contract 2 Quote */
            contract_2_quote: string;
            /** Contract 2 Section */
            contract_2_section: string;
            /** Difference */
            difference: number;
        };
        /** FundingWallAsset */
        FundingWallAsset: {
            /** Asset */
            asset: string;
            /** Market Cap Rank */
            market_cap_rank: number | null;
            /** Rates */
            rates: {
                [key: string]: number | null;
            };
        };
        /** FundingWallResponse */
        FundingWallResponse: {
            /** Assets */
            assets: components["schemas"]["FundingWallAsset"][];
            /** Exchanges */
            exchanges: string[];
            /** Timestamp */
            timestamp: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoricalAvgEntry */
        HistoricalAvgEntry: {
            /** Asset Name */
            asset_name: string;
            /**
             * Contract Id
             * Format: uuid
             */
            contract_id: string;
            /** Funding Interval */
            funding_interval: number;
            /** Quote Name */
            quote_name: string;
            /** Section Name */
            section_name: string;
            /** Windows */
            windows: components["schemas"]["HistoricalAvgWindow"][];
        };
        /** HistoricalAvgWindow */
        HistoricalAvgWindow: {
            /** Days */
            days: number;
            /** Expected Count */
            expected_count: number;
            /** Funding Rate */
            funding_rate: number | null;
            /** Oldest Timestamp */
            oldest_timestamp: number | null;
            /** Points Count */
            points_count: number;
        };
        /** LatestFundingPoint */
        LatestFundingPoint: {
            /** Asset Name */
            asset_name: string;
            /**
             * Contract Id
             * Format: uuid
             */
            contract_id: string;
            /** Funding Interval */
            funding_interval: number;
            /** Funding Rate */
            funding_rate: number;
            /** Quote Name */
            quote_name: string;
            /** Section Name */
            section_name: string;
            /** Timestamp */
            timestamp: number;
        };
        /**
         * NormalizeToInterval
         * @enum {string}
         */
        NormalizeToInterval: "raw" | "1h" | "8h" | "1d" | "365d";
        /** PaginatedCumulativeFundingDifference */
        PaginatedCumulativeFundingDifference: {
            /** Data */
            data: components["schemas"]["CumulativeFundingDifference"][];
            /** Has More */
            has_more: boolean;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total Count */
            total_count: number;
        };
        /** PaginatedFundingRateDifference */
        PaginatedFundingRateDifference: {
            /** Data */
            data: components["schemas"]["FundingRateDifference"][];
            /** Has More */
            has_more: boolean;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total Count */
            total_count: number;
        };
        /** QuoteNames */
        QuoteNames: {
            /** Names */
            names: string[];
        };
        /** SectionNames */
        SectionNames: {
            /** Names */
            names: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    historical_cumulative_differences_api_v0_funding_data_diff_historical_cumulative_differences_get: {
        parameters: {
            query: {
                asset_names?: string[] | null;
                section_names?: string[] | null;
                quote_names?: string[] | null;
                compare_for_section?: string | null;
                min_diff?: number | null;
                buffer_minutes?: number;
                offset?: number;
                limit?: number;
                from_ts: number;
                to_ts: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCumulativeFundingDifference"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    historical_funding_differences_api_v0_funding_data_diff_historical_differences_get: {
        parameters: {
            query: {
                normalize_to_interval?: components["schemas"]["NormalizeToInterval"];
                asset_names?: string[] | null;
                section_names?: string[] | null;
                quote_names?: string[] | null;
                compare_for_section?: string | null;
                min_diff?: number | null;
                buffer_minutes?: number;
                offset?: number;
                limit?: number;
                from_ts: number;
                to_ts: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCumulativeFundingDifference"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    funding_rate_differences_api_v0_funding_data_diff_live_differences_get: {
        parameters: {
            query?: {
                /** @description List of asset names to filter by. 'all' or leave empty for all assets. */
                asset_names?: string[] | null;
                /** @description List of section names to filter by. 'all' or leave empty for all sections. */
                section_names?: string[] | null;
                /** @description List of quote currency names to filter by. 'all' or leave empty for all quotes. */
                quote_names?: string[] | null;
                normalize_to_interval?: components["schemas"]["NormalizeToInterval"];
                /** @description A specific section to compare against all others. */
                compare_for_section?: string | null;
                /** @description Minimum absolute difference to filter results. Only differences >= min_diff will be returned. */
                min_diff?: number | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFundingRateDifference"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    funding_wall_api_v0_funding_data_funding_wall_get: {
        parameters: {
            query: {
                period: "live" | "historical";
                /** @description List of asset names to filter by */
                assets: string[];
                /** @description List of exchange names to filter by */
                exchanges: string[];
                /** @description Normalization interval */
                normalize: components["schemas"]["NormalizeToInterval"];
                from_ts?: number | null;
                to_ts?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundingWallResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    historical_avg_api_v0_funding_data_historical_avg_get: {
        parameters: {
            query: {
                normalize_to_interval?: components["schemas"]["NormalizeToInterval"];
                asset_names?: string[] | null;
                section_names?: string[] | null;
                quote_names?: string[] | null;
                /** @description Window sizes in days, e.g. 7 30 90 */
                windows: number[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalAvgEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    historical_latest_api_v0_funding_data_historical_latest_get: {
        parameters: {
            query?: {
                normalize_to_interval?: components["schemas"]["NormalizeToInterval"];
                asset_names?: string[] | null;
                section_names?: string[] | null;
                quote_names?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestFundingPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    historical_points_api_v0_funding_data_historical_points_get: {
        parameters: {
            query: {
                contract_id: string;
                normalize_to_interval?: components["schemas"]["NormalizeToInterval"];
                from_ts: number;
                to_ts: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundingPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_latest_api_v0_funding_data_live_latest_get: {
        parameters: {
            query?: {
                normalize_to_interval?: components["schemas"]["NormalizeToInterval"];
                asset_names?: string[] | null;
                section_names?: string[] | null;
                quote_names?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestFundingPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_points_api_v0_funding_data_live_points_get: {
        parameters: {
            query: {
                contract_id: string;
                normalize_to_interval?: components["schemas"]["NormalizeToInterval"];
                from_ts: number;
                to_ts: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundingPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    period_sums_api_v0_funding_data_period_sums__contract_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundingPeriodSums"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assets_api_v0_meta_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponse_AssetNames_"];
                };
            };
        };
    };
    search_contracts_api_v0_meta_contracts_search_get: {
        parameters: {
            query: {
                query: string;
                limit?: number;
                debug?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponse_ContractSearchResults_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_meta_api_v0_meta_contracts__contract_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponse_ContractMeta_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quotes_api_v0_meta_quotes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponse_QuoteNames_"];
                };
            };
        };
    };
    get_sections_api_v0_meta_sections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponse_SectionNames_"];
                };
            };
        };
    };
    healthcheck_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
